language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  - OCAML_VERSION=4.06 DISTRO="ubuntu-16.04" PACKAGE=kicadsch
  - PINS="kicadsch.dev:. plotkicadsch.dev:." OCAML_VERSION=4.06 DISTRO="ubuntu-16.04" PACKAGE=plotkicadsch
